# Generated by Django 4.0 on 2022-10-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShukatuPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='企業名')),
                ('myPageId', models.CharField(max_length=100, verbose_name='myPageId')),
                ('myPageUrl', models.URLField(max_length=255, verbose_name='myPageUrl')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('category', models.CharField(blank=True, choices=[('maker', 'メーカー'), ('trading company', '商社'), ('retail', '小売'), ('finance', '金融'), ('service', 'サービス'), ('mass media', 'マスコミ'), ('IT', 'IT'), ('government office', '官公庁・公社・団体'), ('others', 'その他')], max_length=50, null=True, verbose_name='カテゴリ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='ログインユーザー')),
            ],
        ),
    ]
