# Generated by Django 4.0 on 2022-10-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shukatu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shukatupost',
            name='myPageUrl',
            field=models.CharField(max_length=255, verbose_name='myPageUrl'),
        ),
    ]
